// contentStructure.js
// مهمتك: املأ حقول driveLink الفارغة بالروابط الصحيحة.

const structuredContent = {
    "1": {
        "biochemistry": {
            lessons: [
                { title: "Glucides", driveLink: "" }, { title: "Lipides", driveLink: "" }, { title: "Acides aminés, peptides et protéines", driveLink: "" }, { title: "Enzymologie", driveLink: "" }, { title: "Métabolisme des glucides", driveLink: "" }, { title: "Métabolisme des lipides", driveLink: "" }, { title: "Métabolisme des acides aminés", driveLink: "" }, { title: "Bioénergétique", driveLink: "" }
            ]
        },
        "anatomy-y1": {
            lessons: [
                { title: "Introduction à l'anatomie", driveLink: "" }, { title: "Généralités sur l'ostéologie", driveLink: "" }, { title: "Le système articulaire", driveLink: "" }, { title: "Le système musculaire", driveLink: "" }, { title: "Système nerveux", driveLink: "" }, { title: "Anatomie de l’appareil respiratoire", driveLink: "" }, { title: "Appareil cardio-vasculaire", driveLink: "" }, { title: "Le système digestif", driveLink: "" }, { title: "Système reproducteur", driveLink: "" }, { title: "Système urinaire", driveLink: "" }, { title: "Organes des sens", driveLink: "" }, { title: "Système glandulaire endocrinien", driveLink: "" }, { title: "Système tégumentaire (peau et ses annexes)", driveLink: "" }, { title: "Structure du crâne", driveLink: "" }, { title: "Mandibule", driveLink: "" }, { title: "Articulation temporo-mandibulaire (ATM)", driveLink: "" }, { title: "Anatomie topographique de la tête et du cou", driveLink: "" }
            ]
        },
        "embryology": {
            lessons: [
                { title: "Introduction à l'embryologie / Les divisions cellulaires (mitose, méiose)", driveLink: "" }, { title: "La gamétogenèse : Spermatogenèse", driveLink: "" }, { title: "Ovogenèse, folliculogenèse et ovulation", driveLink: "" }, { title: "La première semaine du développement embryonnaire", driveLink: "" }, { title: "La deuxième semaine du développement embryonnaire", driveLink: "" }, { title: "La troisième semaine du développement embryonnaire", driveLink: "" }, { title: "Le développement embryonnaire (4ème semaine)", driveLink: "" }, { title: "L'appareil branchial", driveLink: "" }, { title: "Les malformations congénitales", driveLink: "" }, { title: "Les annexes embryonnaires", driveLink: "" }
            ]
        },
        "histology-y1": {
            lessons: [
                { title: "Introduction à l'histologie et techniques d'étude", driveLink: "" }, { title: "Tissus épithéliaux", driveLink: "" }, { title: "Tissu conjonctif", driveLink: "" }, { title: "Tissu osseux", driveLink: "" }, { title: "Tissus musculaires", driveLink: "" }, { title: "Tissu sanguin", driveLink: "" }, { title: "Tissu nerveux", driveLink: "" }
            ]
        },
        "genetics": {
            lessons: [
                { title: "Introduction à la génétique", driveLink: "" }, { title: "Monohybridisme", driveLink: "" }, { title: "Dihybridisme", driveLink: "" }, { title: "Modes de transmission héréditaires", driveLink: "" }, { title: "Hérédité monogénique", driveLink: "" }, { title: "Caryotype et anomalies chromosomiques", driveLink: "" }, { title: "Acides ribonucléiques (ARN)", driveLink: "" }, { title: "Réplication de l'ADN", driveLink: "" }, { title: "Transcription", driveLink: "" }, { title: "Traduction", driveLink: "" }, { title: "Mutations de l'ADN", driveLink: "" }, { title: "Régulation de l'expression génique", driveLink: "" }, { title: "Gènes des globines", driveLink: "" }, { title: "Outils de la biologie moléculaire", driveLink: "" }, { title: "Structure et organisation du génome humain", driveLink: "" }, { title: "Transfert des gènes chez les bactéries", driveLink: "" }
            ]
        },
        "chemistry1": {
            lessons: [
                { title: "Structure de la matière et des atomes", driveLink: "" }, { title: "Structure électronique et tableau périodique", driveLink: "" }, { title: "Liaisons chimiques", driveLink: "" }, { title: "Chimie organique", driveLink: "" }, { title: "Cinétique chimique", driveLink: "" }, { title: "Thermochimie", driveLink: "" }, { title: "Équilibres chimiques", driveLink: "" }, { title: "Acides et bases", driveLink: "" }, { title: "La solubilité", driveLink: "" }
            ]
        },
        "physics": {
            lessons: [
                { title: "Électrostatique", driveLink: "" }, { title: "Électrocinétique", driveLink: "" }, { title: "Électrophysiologie cellulaire", driveLink: "" }, { title: "Optique géométrique", driveLink: "" }
            ]
        },
        "physiology": {
            lessons: [
                { title: "Vue globale sur la physiologie cardiaque", driveLink: "" }, { title: "Généralités sur la physiologie digestive", driveLink: "" }, { title: "Généralités physio-digestive", driveLink: "" }, { title: "Cours physio-respiratoire", driveLink: "" }, { title: "SNC partie", driveLink: "" }, { title: "Physiologie rénale", driveLink: "" }, { title: "Groupes sanguins", driveLink: "" }, { title: "Physiologie musculaire", driveLink: "" }, { title: "Milieu intérieur", driveLink: "" }, { title: "Physiologie du sang", driveLink: "" }
            ]
        },
        "biophysique": {
            lessons: [
                { title: "Biophysique des solutions", driveLink: "" }, { title: "Biomécanique des fluides", driveLink: "" }, { title: "Biophysique des rayonnements", driveLink: "" }, { title: "Ondes sonores et ultrasonores", driveLink: "" }
            ]
        },
        "ssh": {
            lessons: [
                { title: "Santé et société", driveLink: "" }, { title: "Facteurs influençant la santé et la biodiversité", driveLink: "" }, { title: "Relation soignant-soigné et concepts humains", driveLink: "" }
            ]
        },
        "cytology": { lessons: [] }, "biomathematiques": { lessons: [] }
    },
    "2": {
        "odf-y2": { lessons: [] }, "prothese-y2": { lessons: [] }, "oce": { lessons: [] }, "paro-y2": { lessons: [] }, "patho": { lessons: [] }, "biomateriau": { lessons: [] }, "immunologie": { lessons: [] }, "histology-y2": { lessons: [] }, "hygiene": { lessons: [] }, "microbiologie": { lessons: [] }, "anatomie-humaine": { lessons: [] }, "informatique": { lessons: [] }
    },
    "3": {
         "anatomo-pathologie": {
            lessons: [ { title: "Anatomie et cytologie pathologiques", driveLink: "" }, { title: "Pathologie cellulaire et tissulaire", driveLink: "" }, { title: "Pathologie des substances intercellulaires", driveLink: "" }, { title: "L'inflammation chronique", driveLink: "" }, { title: "Généralités sur les tumeurs", driveLink: "" }, { title: "Les tumeurs bénignes", driveLink: "" }, { title: "Le tissu cancéreux", driveLink: "" }, { title: "Les tumeurs épithéliales", driveLink: "" }, { title: "Les tumeurs des tissus conjonctifs", driveLink: "" }, { title: "Pathologie de la cavité buccale", driveLink: "" }, { title: "Pathologie des glandes salivaires", driveLink: "" } ]
        }, "anesthesiologie": {
            lessons: [ { title: "Pharmacologie de l'anesthésie générale", driveLink: "" }, { title: "Accidents et incidents de l'anesthésie générale", driveLink: "" }, { title: "Indications et contre-indications de l'anesthésie générale", driveLink: "" }, { title: "Examen préopératoire, prémédication et préparation du patient à l'anesthésie générale", driveLink: "" }, { title: "Structures anatomiques impliquées en anesthésie loco-régionale", driveLink: "" }, { title: "Pharmacologie des anesthésiques locaux", driveLink: "" }, { title: "Indications et contre-indications des anesthésiques locaux", driveLink: "" }, { title: "Accidents toxiques des anesthésiques locaux", driveLink: "" } ]
        }, "imagrie": {
            lessons: [ { title: "Introduction à la radiologie", driveLink: "" }, { title: "Principes fondamentaux de la radiologie", driveLink: "" }, { title: "Appareils à rayons X", driveLink: "" }, { title: "Production et émission des rayons X, interaction avec la matière", driveLink: "" }, { title: "Formation de l'image, mathématiques de l'exposition et films radiographiques", driveLink: "" }, { title: "Facteurs influençant la qualité de l'image radiographique", driveLink: "" }, { title: "Le film dentaire : supports, critères de choix, traitements", driveLink: "" }, { title: "Contrôle de la qualité en radiologie dentaire", driveLink: "" }, { title: "Biologie de la radiation et protection du patient et de l'opérateur", driveLink: "" }, { title: "Techniques conventionnelles d'imagerie", driveLink: "" }, { title: "Repères anatomiques sur radiographies endobuccales et exobuccales", driveLink: "" }, { title: "L'imagerie numérique : principes et intérêts", driveLink: "" }, { title: "Tomodensitométrie (scanner à rayons X) : principes, acquisition et mise au point de l'image", driveLink: "" }, { title: "Tomographie volumique par faisceau conique (Cone Beam)", driveLink: "" }, { title: "Imagerie par résonance magnétique (IRM) : principes, acquisition d'image, traitement et archivage", driveLink: "" }, { title: "Dosimétrie et radioprotection en imagerie cranio-dentaire", driveLink: "" } ]
        }, "oc": {
            lessons: [ { title: "L'endodontie : généralités, buts, principes et cavités d'accès", driveLink: "" }, { title: "Moyens et conduite diagnostique en odontologie", driveLink: "" }, { title: "Désinfection, stérilisation, asepsie et antisepsie", driveLink: "" }, { title: "L'insensibilisation dentaire en odontologie", driveLink: "" }, { title: "L'instrumentation en endodontie", driveLink: "" }, { title: "La pharmacologie endodontique", driveLink: "" }, { title: "Les atteintes pulpo-dentinaires", driveLink: "" }, { title: "Les mortifications pulpaires", driveLink: "" }, { title: "Les préparations canalaires : différentes techniques", driveLink: "" }, { title: "Pathologies pulpaires : pulpites asymptomatiques et symptomatiques", driveLink: "" }, { title: "Protections dentino-pulpaires et thérapeutiques bio-conservatrices des dentinites (les coiffages pulpaires)", driveLink: "" }, { title: "Sensibilité et hypersensibilité dentinaire", driveLink: "" } ]
        }, "occlusio": {
            lessons: [ { title: "Occlusion : généralités et terminologie", driveLink: "" }, { title: "Anatomie physiologique", driveLink: "" }, { title: "Occlusion clinique", driveLink: "" }, { title: "Approche clinique et moyens de diagnostic", driveLink: "" }, { title: "Les dysfonctionnements de l'appareil manducateur", driveLink: "" }, { title: "Conceptions thérapeutiques générales et prévention", driveLink: "" } ]
        }, "odf-y3": {
            lessons: [ { title: "La terminologie en ODF", driveLink: "" }, { title: "L'examen clinique en ODF", driveLink: "" }, { title: "Le dossier orthodontique", driveLink: "" }, { title: "La céphalométrie", driveLink: "" }, { title: "Physiologie de l'occlusion chez l'enfant", driveLink: "" }, { title: "Les étiologies des anomalies dento-maxillo-faciales", driveLink: "" }, { title: "Étude diagnostique des anomalies dentaires de nombre (excès ou défaut)", driveLink: "" }, { title: "Étude diagnostique des dents incluses", driveLink: "" }, { title: "Étude diagnostique de la dysharmonie dento-maxillaire et dento-dentaire", driveLink: "" }, { title: "Diagnostic des anomalies dento-alvéolaires du sens transversal", driveLink: "" }, { title: "Diagnostic des anomalies dento-alvéolaires du sens vertical", driveLink: "" }, { title: "Diagnostic des anomalies dento-alvéolaires du sens sagittal", driveLink: "" }, { title: "Diagnostic des anomalies basales du sens transversal", driveLink: "" }, { title: "Diagnostic des anomalies basales du sens vertical", driveLink: "" }, { title: "Diagnostic des anomalies basales du sens sagittal : La classe II/1", driveLink: "" }, { title: "Diagnostic des anomalies basales du sens sagittal : La classe II/2", driveLink: "" }, { title: "Diagnostic des anomalies basales du sens sagittal : La classe III", driveLink: "" }, { title: "Les grands syndromes en ODF", driveLink: "" }, { title: "La biomécanique appliquée à l'ODF", driveLink: "" }, { title: "Réactions tissulaires au cours du déplacement dentaire", driveLink: "" } ]
        }, "oxyologie": {
            lessons: [ { title: "Introduction à l'oxyologie", driveLink: "" }, { title: "Matériel de réanimation et drogues d'urgence", driveLink: "" }, { title: "CAT devant une détresse respiratoire", driveLink: "" }, { title: "CAT devant une détresse cardio-circulatoire", driveLink: "" }, { title: "CAT devant une détresse neurologique", driveLink: "" }, { title: "Crise d'épilepsie et crise convulsive", driveLink: "" }, { title: "Choc anaphylactique et anaphylaxie", driveLink: "" }, { title: "CAT devant une inhalation et ingestion d'un corps étranger", driveLink: "" }, { title: "Hémorragie au cabinet dentaire", driveLink: "" } ]
        }, "paro-y3": {
            lessons: [ { title: "Étiologies des maladies parodontales", driveLink: "" }, { title: "Inflammation et histopathogénie des maladies parodontales", driveLink: "" }, { title: "Classifications des maladies parodontales et formes cliniques", driveLink: "" }, { title: "La poche parodontale", driveLink: "" }, { title: "Troubles gingivaux", driveLink: "" }, { title: "Les parodontites", driveLink: "" }, { title: "Les urgences parodontales", driveLink: "" }, { title: "Maladies parodontales et maladies générales", driveLink: "" }, { title: "Épidémiologie des maladies parodontales", driveLink: "" }, { title: "Clinique d'examen en parodontologie", driveLink: "" }, { title: "Détartrage-surfaçage radiculaire", driveLink: "" }, { title: "Prescription médicamenteuse en parodontologie", driveLink: "" }, { title: "Prévention des maladies parodontales", driveLink: "" }, { title: "Entretien parodontal", driveLink: "" } ]
        }, "pathologie-y3": {
            lessons: [ { title: "Physiopathologie de l'infection", driveLink: "" }, { title: "Physiopathologie de l'inflammation", driveLink: "" }, { title: "Physiopathologie de la douleur", driveLink: "" }, { title: "Cellulites cervico-faciales d'origine dentaire", driveLink: "" }, { title: "Les ostéites des maxillaires", driveLink: "" }, { title: "Ostéoradionécrose / Ostéonécroses dues aux bisphosphonates", driveLink: "" }, { title: "Dents et sinus", driveLink: "" }, { title: "Manifestations à distance des foyers bucco-dentaires", driveLink: "" }, { title: "Septicémies et thrombophlébites cranio-faciales", driveLink: "" }, { title: "Les antibiotiques", driveLink: "" }, { title: "Les anti-inflammatoires (AINS et AIS)", driveLink: "" }, { title: "Les antalgiques et les vitamines", driveLink: "" }, { title: "Explorations biologiques", driveLink: "" }, { title: "Explorations radiologiques", driveLink: "" }, { title: "Les lésions élémentaires", driveLink: "" }, { title: "Aphtes et aphtoses", driveLink: "" }, { title: "Les mycoses de la cavité buccale", driveLink: "" }, { title: "Les infections spécifiques de la muqueuse buccale", driveLink: "" }, { title: "Les douleurs oro-faciales", driveLink: "" }, { title: "Les paralysies faciales", driveLink: "" }, { title: "Tumeurs bénignes de la muqueuse buccale", driveLink: "" }, { title: "Tumeurs bénignes des maxillaires", driveLink: "" }, { title: "Les kystes des maxillaires", driveLink: "" }, { title: "Les urgences au cabinet dentaire et notions de réanimation", driveLink: "" } ]
        }, "pharmacologie": {
            lessons: [ { title: "Introduction à la pharmacologie", driveLink: "" }, { title: "Pharmacologie générale", driveLink: "" }, { title: "Pharmacocinétique : Absorption", driveLink: "" }, { title: "Pharmacocinétique : Distribution", driveLink: "" }, { title: "Pharmacocinétique : Métabolisme", driveLink: "" }, { title: "Pharmacocinétique : Élimination", driveLink: "" }, { title: "Cibles des médicaments", driveLink: "" }, { title: "Pharmacodynamie et pharmacométrie", driveLink: "" }, { title: "Facteurs modifiant l'activité des médicaments", driveLink: "" }, { title: "Les interactions médicamenteuses", driveLink: "" }, { title: "Effets indésirables des médicaments", driveLink: "" }, { title: "AIS", driveLink: "" }, { title: "AINS", driveLink: "" }, { title: "Système nerveux central", driveLink: "" }, { title: "Système nerveux autonome", driveLink: "" }, { title: "Médicaments de la douleur et incidences odontologiques : les analgésiques et les anti-infectieux", driveLink: "" }, { title: "Antibiotiques", driveLink: "" }, { title: "Antibiotiques : incidence odontologique", driveLink: "" }, { title: "Antifongiques", driveLink: "" }, { title: "Antiseptiques", driveLink: "" }, { title: "Médicaments des troubles de l'hémostase et incidences odontologiques", driveLink: "" }, { title: "Médicaments de l'appareil cardio-vasculaire et odontologie", driveLink: "" }, { title: "Médicaments de l'appareil urinaire et incidences odontologiques", driveLink: "" }, { title: "Médicaments de l'appareil digestif et incidences odontologiques", driveLink: "" }, { title: "Médicaments de l'appareil respiratoire et incidences odontologiques", driveLink: "" }, { title: "Les hypoglycémiants et incidences odontologiques", driveLink: "" }, { title: "Les médicaments de l'urgence au cabinet dentaire", driveLink: "" } ]
        }, "prothese-y3": {
            lessons: [ { title: "Ostéologie, myologie et physiologie de la cavité buccale totalement édentée", driveLink: "" }, { title: "L'observation clinique", driveLink: "" }, { title: "Apport de la chirurgie pré-prothétique au niveau des tissus mous et des tissus durs", driveLink: "" }, { title: "La mise en condition tissulaire et neuro-articulo-musculaire", driveLink: "" }, { title: "Les empreintes primaires et leurs traitements", driveLink: "" }, { title: "Les empreintes secondaires et leurs traitements", driveLink: "" }, { title: "Le plan d'occlusion", driveLink: "" }, { title: "Les dimensions verticales", driveLink: "" }, { title: "La relation centrée", driveLink: "" }, { title: "Les articulateurs semi-adaptables et arcs faciaux", driveLink: "" }, { title: "L'occlusion bilatérale équilibrée", driveLink: "" }, { title: "La résorption osseuse : choix et montage des dents", driveLink: "" }, { title: "L'essai fonctionnel en bouche des maquettes de montage", driveLink: "" }, { title: "La polymérisation et la finition des prothèses complètes", driveLink: "" }, { title: "L'insertion en bouche et conseils post-prothétiques", driveLink: "" }, { title: "La stabilisation des prothèses par les empreintes tertiaires", driveLink: "" }, { title: "Les équilibrations occlusales immédiates et médiates", driveLink: "" }, { title: "Adhésion, rétention et sustentation en prothèse adjointe complète", driveLink: "" }, { title: "Les prothèses immédiates (provisoires et d'usage)", driveLink: "" }, { title: "Les prothèses piézographiques", driveLink: "" }, { title: "La réfection des bases prothétiques", driveLink: "" }, { title: "Les prothèses amovibles complètes supra-implantaires", driveLink: "" }, { title: "Les bases souples permanentes", driveLink: "" }, { title: "L'édentement total unimaxillaire", driveLink: "" } ]
        }
    },
    "4": {
         "deontologie": {
            lessons: [ { title: "Déontologie médicale et éthique, code de la déontologie dentaire", driveLink: "" }, { title: "Ordre des médecins-dentistes", driveLink: "" }, { title: "Organisation judiciaire et son fonctionnement", driveLink: "" }, { title: "Secret professionnel et certificats médicaux", driveLink: "" }, { title: "Les institutions internationales, relation praticien-malade, consentement éclairé", driveLink: "" }, { title: "Droit de prescription des médecins-dentistes", driveLink: "" }, { title: "Odontologie légale, exercice légal et illégal de la médecine dentaire", driveLink: "" }, { title: "Les médicaments génériques : autorisation de mise sur le marché", driveLink: "" }, { title: "Relation praticien-confrère, nomenclature des actes professionnels", driveLink: "" }, { title: "Sécurité sociale : mission et rôles, médecin-conseil, tarification", driveLink: "" }, { title: "Odontologie médico-légale : expertise et identification", driveLink: "" } ]
        }, "implanto": {
            lessons: [ { title: "Introduction à l'implantologie orale", driveLink: "" }, { title: "L'ostéointégration", driveLink: "" }, { title: "Rappels sur les bases fondamentales de l'anatomie et de la physiologie osseuse", driveLink: "" }, { title: "Biomécanique implantaire", driveLink: "" }, { title: "Le système implantaire", driveLink: "" }, { title: "Bilan pré-implantaire", driveLink: "" }, { title: "Le dossier clinique", driveLink: "" }, { title: "Moyens de diagnostic complémentaires", driveLink: "" }, { title: "Contre-indications du traitement implantaire", driveLink: "" }, { title: "Stratégies thérapeutiques et notions de consentement éclairé en implantologie", driveLink: "" }, { title: "Notions d'aménagement tissulaire pré-implantaire", driveLink: "" } ]
        }, "oce-y4": {
            lessons: [ { title: "La cicatrisation dentino-pulpaire", driveLink: "" }, { title: "Indications et contre-indications des traitements endodontiques", driveLink: "" }, { title: "La cicatrisation apicale", driveLink: "" }, { title: "Accidents et incidents survenant lors des thérapeutiques en odontologie conservatrice-endodontie", driveLink: "" }, { title: "Les urgences en odontologie conservatrice-endodontie", driveLink: "" }, { title: "Les traumatismes alvéolo-dentaires : données étiologiques, épidémiologiques, classification, 1ère consultation et diagnostic", driveLink: "" }, { title: "Prise en charge des traumatismes dentaires", driveLink: "" }, { title: "Évaluation de la situation clinique et du besoin thérapeutique, prévention et traitement des pathologies iatrogènes", driveLink: "" }, { title: "La dentisterie préventive et/ou non invasive", driveLink: "" }, { title: "Reconstitutions complexes des dents : moyens d'ancrages et techniques", driveLink: "" }, { title: "Thérapeutiques esthétiques des dyschromies dentaires sur dents vitales et dents mortifiées : facettes collées, éclaircissement chimique", driveLink: "" } ]
        }, "odf-y4": {
            lessons: [ { title: "La place du diagnostic dans le plan de traitement en ODF", driveLink: "" }, { title: "Les objectifs de traitement en ODF et critères de décision", driveLink: "" }, { title: "La rééducation neuromusculaire des fonctions orofaciales", driveLink: "" }, { title: "Traitement des inclusions dentaires", driveLink: "" }, { title: "La thérapeutique amovible en ODF", driveLink: "" }, { title: "Traitement des agénésies dentaires", driveLink: "" }, { title: "Traitement de la dysharmonie dento-maxillaire et dento-dentaire", driveLink: "" }, { title: "Traitement des anomalies alvéolaires du sens sagittal, vertical et transversal", driveLink: "" }, { title: "Traitement des anomalies basales du sens sagittal : la classe II div 1", driveLink: "" }, { title: "Traitement de la classe II div 2", driveLink: "" }, { title: "Traitement de la classe III", driveLink: "" }, { title: "Traitement des anomalies basales du sens vertical", driveLink: "" }, { title: "Traitement des anomalies basales du sens transversal", driveLink: "" }, { title: "Les forces extra-buccales et élastiques intermaxillaires", driveLink: "" }, { title: "La thérapeutique fonctionnelle", driveLink: "" }, { title: "La thérapeutique orthopédique", driveLink: "" }, { title: "La thérapeutique orthodontico-chirurgicale", driveLink: "" }, { title: "Thérapeutiques fixées : l'Edgewise standard", driveLink: "" }, { title: "Les techniques de l'arc droit : Andrews, Roth, Tip-Edge", driveLink: "" }, { title: "Les techniques bioprogressives de Ricketts", driveLink: "" }, { title: "L'orthodontie invisible : technique linguale, Invisalign", driveLink: "" }, { title: "Critères de fin de traitement et équilibration occlusale post-orthodontique", driveLink: "" }, { title: "Contention et récidive", driveLink: "" }, { title: "L'orthodontie de l'adulte", driveLink: "" } ]
        }, "og": {
            lessons: [ { title: "Notions générales sur le vieillissement et la sénescence de la cavité buccale, le vieillissement des fonctions", driveLink: "" }, { title: "Spécificités de l'examen clinique chez le sujet âgé", driveLink: "" }, { title: "Sécheresse buccale et hyposialie", driveLink: "" }, { title: "Les pathologies générales dégénératives du sujet âgé", driveLink: "" }, { title: "Soins conservateurs et endodontiques chez le sujet âgé", driveLink: "" }, { title: "Traitements parodontaux chez le sujet âgé", driveLink: "" }, { title: "Réhabilitation prothétique chez le sujet âgé", driveLink: "" }, { title: "Traitement implantaire chez le sujet âgé", driveLink: "" }, { title: "Soins à domicile chez le sujet âgé", driveLink: "" }, { title: "Prescriptions et interactions médicamenteuses chez le sujet âgé", driveLink: "" }, { title: "Douleurs oro-faciales chez le sujet âgé", driveLink: "" } ]
        }, "op": {
            lessons: [ { title: "Introduction à l'odontologie pédiatrique, approche psychologique de l'enfant", driveLink: "" }, { title: "Morphologie, histophysiologie et physiopathologie des dents temporaires et permanentes immatures", driveLink: "" }, { title: "Parodonte de l'enfant : particularités", driveLink: "" }, { title: "Pathologie des dents temporaires", driveLink: "" }, { title: "Pathologie des dents permanentes immatures", driveLink: "" }, { title: "Accidents d'éruption et d'évolution des dents", driveLink: "" }, { title: "Ergonomie et matériel spécifique en odontologie pédiatrique", driveLink: "" }, { title: "L'examen clinique en odontologie pédiatrique", driveLink: "" }, { title: "Explorations radiologiques en odontologie pédiatrique", driveLink: "" }, { title: "Les dents de 6 ans", driveLink: "" }, { title: "Anesthésie en pédodontie", driveLink: "" }, { title: "Aspects cliniques de l'odontologie restauratrice chez l'enfant et l'adolescent", driveLink: "" }, { title: "Sémiologie en pédodontie", driveLink: "" }, { title: "Thérapeutiques préventives en dentisterie pédiatrique", driveLink: "" }, { title: "Approches thérapeutiques selon l'âge de l'enfant et la dent causale", driveLink: "" } ]
        }, "paro-y4": {
            lessons: [ { title: "Conception et organisation du traitement parodontal", driveLink: "" }, { title: "La chirurgie parodontale", driveLink: "" }, { title: "Thérapeutique chirurgicale des maladies gingivales", driveLink: "" }, { title: "Thérapeutique chirurgicale des parodontites", driveLink: "" }, { title: "Les récessions parodontales", driveLink: "" }, { title: "Thérapeutique des défauts du complexe muco-gingival et des récessions parodontales", driveLink: "" }, { title: "Les lésions interradiculaires", driveLink: "" }, { title: "Les défauts osseux parodontaux", driveLink: "" }, { title: "La cicatrisation parodontale", driveLink: "" }, { title: "Le pronostic", driveLink: "" }, { title: "La réévaluation des thérapeutiques parodontales", driveLink: "" } ]
        }, "patho-medical": {
            lessons: [ { title: "Dysthyroïdies et maladies des surrénales", driveLink: "" }, { title: "Diabète et nutrition", driveLink: "" }, { title: "Syndrome hémorragique et anémies", driveLink: "" }, { title: "Maladie thromboembolique veineuse", driveLink: "" }, { title: "Syndrome coronarien aigu", driveLink: "" }, { title: "Urticaire, eczéma et psoriasis", driveLink: "" }, { title: "Endocardite infectieuse et valvulopathies", driveLink: "" }, { title: "Maladies systémiques", driveLink: "" }, { title: "Insuffisance cardiaque", driveLink: "" }, { title: "Ulcère gastroduodénal et colopathie fonctionnelle", driveLink: "" }, { title: "Arthroses, arthrites et prothèses articulaires", driveLink: "" }, { title: "Ostéoporose et ostéomalacie", driveLink: "" }, { title: "Glomérulonéphrites, insuffisance rénale et dialyse", driveLink: "" }, { title: "Septicémies et antibiothérapie", driveLink: "" }, { title: "Asthme et allergies", driveLink: "" }, { title: "Hépatites et cirrhoses", driveLink: "" }, { title: "Céphalées et algies faciales", driveLink: "" }, { title: "Hypertension artérielle et AVC", driveLink: "" }, { title: "Syndrome d'immunodéficience acquise (SIDA)", driveLink: "" }, { title: "Épilepsies", driveLink: "" }, { title: "Les leucémies", driveLink: "" }, { title: "Infections des voies aériennes supérieures (VAS) et vertiges", driveLink: "" }, { title: "Maladies chroniques inflammatoires de l'intestin (MICI)", driveLink: "" } ]
        }, "patho-bucco-dentaire": {
            lessons: [ { title: "Les cardiopathies", driveLink: "" }, { title: "Diabète et troubles endocriniens", driveLink: "" }, { title: "Terrains particuliers : la femme enceinte", driveLink: "" }, { title: "L'insuffisance rénale", driveLink: "" }, { title: "Les hémopathies", driveLink: "" }, { title: "Patients sous chimiothérapie anticancéreuse", driveLink: "" }, { title: "Patients irradiés de la région cervico-faciale", driveLink: "" }, { title: "Patients sous inhibiteurs de la résorption osseuse et anti-angiogéniques", driveLink: "" }, { title: "Patients immunodéprimés", driveLink: "" }, { title: "Les traumatismes alvéolo-dentaires", driveLink: "" }, { title: "Les fractures de la mandibule", driveLink: "" }, { title: "Les fractures du massif facial supérieur", driveLink: "" }, { title: "Traitement des fractures des maxillaires", driveLink: "" }, { title: "Sémiologie et examen spécifique d'un patient atteint de troubles de l'ATM", driveLink: "" }, { title: "Pathologie inflammatoire et dégénérative de l'ATM", driveLink: "" }, { title: "Limitations de l'ouverture buccale : trismus et ankylose temporo-mandibulaire", driveLink: "" }, { title: "Les luxations des ATM", driveLink: "" }, { title: "Introduction à la pathologie salivaire : lithiase des glandes salivaires", driveLink: "" }, { title: "Pathologie inflammatoire des glandes salivaires", driveLink: "" }, { title: "Diagnostic des tumeurs bénignes des glandes salivaires", driveLink: "" }, { title: "Diagnostic des tumeurs malignes des glandes salivaires", driveLink: "" }, { title: "Diagnostic des ulcérations", driveLink: "" }, { title: "Affections bulleuses et vésiculeuses de la muqueuse buccale", driveLink: "" }, { title: "Lésions blanches de la muqueuse buccale", driveLink: "" }, { title: "Lésions pigmentées de la muqueuse buccale", driveLink: "" }, { title: "Les adénopathies cervico-faciales", driveLink: "" }, { title: "Les allergies en odontologie", driveLink: "" } ]
        }, "prothese-y4": {
            lessons: [ { title: "Introduction à la prothèse conjointe", driveLink: "" }, { title: "L'examen clinique et le plan de traitement", driveLink: "" }, { title: "Les principes généraux des préparations", driveLink: "" }, { title: "Les limites cervicales et les profils d'émergence", driveLink: "" }, { title: "La couronne coulée", driveLink: "" }, { title: "La couronne à incrustation vestibulaire (CIV)", driveLink: "" }, { title: "La couronne céramo-métallique (CCM)", driveLink: "" }, { title: "La couronne jacket", driveLink: "" }, { title: "Les ancrages corono-radiculaires : la Richmond et l'inlay-core", driveLink: "" }, { title: "Les ancrages partiels en alliages", driveLink: "" }, { title: "Choix et indications des ancrages", driveLink: "" }, { title: "La classification des ponts (bridges) et principes biomécaniques", driveLink: "" }, { title: "Les intermédiaires de ponts (bridges)", driveLink: "" }, { title: "Les empreintes en prothèse fixée", driveLink: "" }, { title: "Les traitements des empreintes", driveLink: "" }, { title: "Les techniques de réalisation prothétique au laboratoire", driveLink: "" }, { title: "L'occlusion en prothèse conjointe", driveLink: "" }, { title: "Le scellement", driveLink: "" }, { title: "La prothèse conjointe et le parodonte", driveLink: "" }, { title: "Introduction à la prothèse collée", driveLink: "" }, { title: "Les restaurations collées : inlays, onlays et overlays", driveLink: "" }, { title: "Les procédés céramo-céramiques", driveLink: "" }, { title: "CFAO (Conception et Fabrication Assistées par Ordinateur)", driveLink: "" } ]
        }
    },
    "5": {
         "epidemio-y5": {
            lessons: [ { title: "Introduction à l'épidémiologie", driveLink: "" }, { title: "Différentes étapes d'un projet de recherche", driveLink: "" }, { title: "Types d'études épidémiologiques", driveLink: "" }, { title: "Branches de l'épidémiologie", driveLink: "" }, { title: "Indicateurs de santé", driveLink: "" }, { title: "Biostatistiques", driveLink: "" }, { title: "Mesures d'association", driveLink: "" }, { title: "Concepts de santé publique", driveLink: "" }, { title: "Programme national de santé bucco-dentaire en milieu scolaire", driveLink: "" }, { title: "Test d'hypothèse du Khi-deux", driveLink: "" }, { title: "Table de Khi-deux et DDL", driveLink: "" }, { title: "Hygiène de l'eau", driveLink: "" }, { title: "Hygiène de base dans un cabinet dentaire", driveLink: "" } ]
        }, "ergonomie-y5": {
            lessons: [ { title: "Introduction à l'ergonomie", driveLink: "" }, { title: "Conception architecturale d'un cabinet dentaire", driveLink: "" }, { title: "Risques professionnels en médecine dentaire", driveLink: "" }, { title: "Éclairage au cabinet dentaire", driveLink: "" }, { title: "Ergonomie et postures de travail", driveLink: "" }, { title: "La couleur, composante de l'ambiance au cabinet dentaire", driveLink: "" }, { title: "Les accidents du travail et les maladies professionnelles en odontologie", driveLink: "" }, { title: "Matériel dentaire et équipement de travail", driveLink: "" }, { title: "Prévention des risques professionnels et contrôle de l'infection au cabinet dentaire", driveLink: "" } ]
        }, "implanto-y5": {
            lessons: [ { title: "Planification et projet prothétique en implantologie", driveLink: "" }, { title: "Techniques chirurgicales", driveLink: "" }, { title: "Extraction atraumatique", driveLink: "" }, { title: "Notions sur la prothèse implantaire", driveLink: "" }, { title: "Les péri-implantites : clinique et traitement", driveLink: "" }, { title: "Les échecs et complications en implantologie", driveLink: "" } ]
        }, "oce-y5": {
            lessons: [ { title: "Principes de base et techniques en colorimétrie", driveLink: "" }, { title: "Les nouvelles approches diagnostiques", driveLink: "" }, { title: "La dentisterie cosmétique", driveLink: "" }, { title: "Les reconstitutions par stratification", driveLink: "" }, { title: "Les restaurations corono-radiculaires indirectes", driveLink: "" }, { title: "Les retraitements : moyens et techniques", driveLink: "" }, { title: "Les retraitements orthogrades et rétrogrades", driveLink: "" }, { title: "Éviction des bris d'instruments endocanalaires", driveLink: "" }, { title: "Complications loco-régionales d'origine dentaire", driveLink: "" }, { title: "Conduite à tenir et thérapeutiques des complications loco-régionales", driveLink: "" }, { title: "Maladies générales et OCE", driveLink: "" }, { title: "La relation endo-parodontale", driveLink: "" }, { title: "Thérapeutiques des résorptions internes et externes", driveLink: "" }, { title: "Endodontie chirurgicale", driveLink: "" } ]
        }, "odf-y5": {
            lessons: [ { title: "Prévention et interception", driveLink: "" }, { title: "Les fentes labio-palatines", driveLink: "" }, { title: "Orthodontie et dysfonctionnement de l'appareil manducateur", driveLink: "" }, { title: "Le syndrome d'apnée-hypopnée obstructive du sommeil (SAHOS)", driveLink: "" }, { title: "Le rôle de l'orthodontie dans la chirurgie orthognathique", driveLink: "" }, { title: "Les grands syndromes en ODF", driveLink: "" }, { title: "Le diagnostic parodontal en orthodontie", driveLink: "" }, { title: "Le distaliseur actif : concepts", driveLink: "" }, { title: "L'informatique en ODF", driveLink: "" }, { title: "Les interrelations ODF-Paro-Patho-Prothèse", driveLink: "" }, { title: "Interrelations orthodontie-orthophonie-ORL", driveLink: "" }, { title: "Les mini-vis en orthodontie", driveLink: "" }, { title: "La réhabilitation neuro-occlusale (RNO)", driveLink: "" }, { title: "Superpositions et prévisions de croissance", driveLink: "" }, { title: "Les biostatistiques appliquées à l'orthodontie", driveLink: "" } ]
        }, "op-y5": {
            lessons: [ { title: "Prévention et éducation à l'hygiène", driveLink: "" }, { title: "Bilan alimentaire", driveLink: "" }, { title: "Les sealants : séquence et surveillance", driveLink: "" }, { title: "Endodontie des dents temporaires et permanentes immatures", driveLink: "" }, { title: "Conduite d'urgence face à un traumatisme", driveLink: "" }, { title: "Prise en charge des fractures alvéolaires", driveLink: "" }, { title: "Traumatismes des dents temporaires et permanentes immatures et leur prise en charge", driveLink: "" }, { title: "Prise en charge des pathologies bucco-dentaires chez l'enfant handicapé", driveLink: "" }, { title: "Thérapeutique sous anesthésie générale et sous sédation consciente", driveLink: "" }, { title: "Pathologies bucco-dentaires, patients à risques et prise en charge", driveLink: "" }, { title: "Pathologie parodontale chez l'enfant et prise en charge", driveLink: "" }, { title: "Prothèse dentaire infantile", driveLink: "" }, { title: "Le maintien de l'espace après avulsion d'une dent temporaire ou permanente", driveLink: "" }, { title: "Dysfonctions et parafonctions", driveLink: "" }, { title: "Établissement de l'occlusion chez l'enfant", driveLink: "" }, { title: "Prescription médicamenteuse", driveLink: "" } ]
        }, "paro-y5": {
            lessons: [ { title: "La mobilité dentaire", driveLink: "" }, { title: "Les thérapeutiques non chirurgicales", driveLink: "" }, { title: "Les péri-implantites", driveLink: "" }, { title: "Les interrelations parodontie-endodontie", driveLink: "" }, { title: "Les interrelations parodontie-prothèse", driveLink: "" }, { title: "Les interrelations parodontie-orthodontie", driveLink: "" } ]
        }, "patho-y5": {
            lessons: [ { title: "Notions générales de cancérologie", driveLink: "" }, { title: "Prévention et dépistage des cancers de la cavité buccale", driveLink: "" }, { title: "Les lésions potentiellement malignes de la muqueuse buccale", driveLink: "" }, { title: "Carcinomes épidermoïdes de la muqueuse buccale", driveLink: "" }, { title: "Carcinomes des maxillaires", driveLink: "" }, { title: "Sarcomes des maxillaires", driveLink: "" }, { title: "Traitement chirurgical des cancers de la cavité buccale", driveLink: "" }, { title: "Traitement par chimiothérapie des cancers de la cavité buccale", driveLink: "" }, { title: "Le traitement par radiothérapie des cancers de la cavité buccale", driveLink: "" }, { title: "Traitement par thérapie ciblée", driveLink: "" }, { title: "Troubles congénitaux cranio-faciaux du développement", driveLink: "" }, { title: "Ostéopathies des maxillaires", driveLink: "" }, { title: "Les pertes de substance des maxillaires", driveLink: "" }, { title: "Les prothèses maxillo-faciales", driveLink: "" } ]
        }, "prothese-y5": {
            lessons: [ { title: "Les différents éléments d'un châssis métallique", driveLink: "" }, { title: "Traitement des édentements distaux et intercalés en prothèse partielle métallique amovible", driveLink: "" }, { title: "Traitements pré-prothétiques", driveLink: "" }, { title: "Traitement prothétique des édentements distaux", driveLink: "" }, { title: "Traitement prothétique des édentements intercalés", driveLink: "" }, { title: "Traitements post-prothétiques : doléances et maintenance", driveLink: "" }, { title: "Traitement post-prothétique : équilibration occlusale", driveLink: "" }, { title: "Les schémas occlusaux en prothèse partielle métallique amovible", driveLink: "" }, { title: "Les attachements", driveLink: "" }, { title: "La prothèse composite", driveLink: "" }, { title: "Prothèse partielle métallique amovible et tissus de soutien", driveLink: "" }, { title: "La prothèse maxillo-faciale : généralités", driveLink: "" }, { title: "La prothèse maxillo-faciale : salive, radiations ionisantes et prothèse", driveLink: "" }, { title: "La prothèse maxillo-faciale : les empreintes, biomatériaux et techniques", driveLink: "" }, { title: "La prothèse maxillo-faciale : l'apport de l'implantologie", driveLink: "" }, { title: "Passage de l'édentement partiel à l'édentement total", driveLink: "" } ]
        }
    }
};

module.exports = { structuredContent };